"""add users.scoreboard_identity json column

Revision ID: f1e3c3a6182e
Revises: 97ef1128a4ba
Create Date: 2026-05-26 10:10:43.430943

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1e3c3a6182e"
down_revision: str | Sequence[str] | None = "97ef1128a4ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("scoreboard_identity", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "scoreboard_identity")
    # ### end Alembic commands ###
