/**
 * Reclaim disk space dialog.
 *
 * Lets the user pick categories of generated artifacts to delete and
 * shows a running total before they confirm. The audit-data category
 * is destructive (drops the user's audit work) and is segregated in
 * a warning-styled section so it cannot be ticked by accident.
 *
 * Project state (project.json) and the symlinks under raw/ are never
 * touched -- the original sources are safe.
 */

import { useEffect, useState } from "react";
import { Trash2, AlertTriangle } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  ApiError,
  api,
  type CleanupCategory,
  type CleanupPlan,
} from "@/lib/api";

interface CategorySpec {
  category: CleanupCategory;
  label: string;
  help: string;
}

const SAFE_CATEGORIES: CategorySpec[] = [
  {
    category: "caches",
    label: "Caches",
    help: "Thumbnails, ffprobe metadata, scoreboard API cache, waveform peaks. Recreated on demand.",
  },
  {
    category: "exports-light",
    label: "CSV / FCPXML / report",
    help: "Light-weight per-stage outputs. Regenerated by Export.",
  },
  {
    category: "exports-overlays",
    label: "Overlay MOVs",
    help: "Pre-rendered alpha overlays (V2 track in FCP). Largest single category.",
  },
  {
    category: "exports-trims",
    label: "Lossless trims",
    help: "Final-Cut-bound trimmed MP4s under exports/. Includes per-camera trims.",
  },
  {
    category: "audit-trims",
    label: "Audit-mode trims",
    help: "Short-GOP scrub copies under trimmed/. Re-encoded by the audit screen on next open.",
  },
  {
    category: "audio",
    label: "Extracted audio",
    help: "WAV files extracted from source video for detection. Re-extracted on next detect run.",
  },
];

const AUDIT_CATEGORY: CategorySpec = {
  category: "audit-data",
  label: "Audit JSON + .bak backups",
  help: "DESTRUCTIVE. Deletes per-stage shot audit work. Cannot be recreated -- you would re-audit from scratch.",
};

function formatBytes(bytes: number): string {
  if (bytes <= 0) return "0 B";
  const units = ["B", "KB", "MB", "GB", "TB"];
  let value = bytes;
  let unit = 0;
  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024;
    unit += 1;
  }
  return `${value.toFixed(value >= 100 || unit === 0 ? 0 : 1)} ${units[unit]}`;
}

interface CleanupDialogProps {
  onClose: () => void;
}

type ApplyOutcome = {
  bytesFreed: number;
  deleted: number;
  failed: number;
} | null;

export function CleanupDialog({ onClose }: CleanupDialogProps) {
  const [selected, setSelected] = useState<Set<CleanupCategory>>(new Set());
  const [plan, setPlan] = useState<CleanupPlan | null>(null);
  const [planLoading, setPlanLoading] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [outcome, setOutcome] = useState<ApplyOutcome>(null);

  useEffect(() => {
    if (outcome) return;
    if (selected.size === 0) {
      setPlan(null);
      return;
    }
    let cancelled = false;
    const handle = window.setTimeout(async () => {
      setPlanLoading(true);
      try {
        const fresh = await api.getCleanupPlan(Array.from(selected));
        if (!cancelled) setPlan(fresh);
      } catch (e) {
        if (!cancelled) setError(e instanceof Error ? e.message : String(e));
      } finally {
        if (!cancelled) setPlanLoading(false);
      }
    }, 120);
    return () => {
      cancelled = true;
      window.clearTimeout(handle);
    };
  }, [selected, outcome]);

  const toggle = (cat: CleanupCategory) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(cat)) next.delete(cat);
      else next.add(cat);
      return next;
    });
  };

  const selectAllSafe = () => {
    setSelected(new Set(SAFE_CATEGORIES.map((s) => s.category)));
  };

  const deselectAll = () => setSelected(new Set());

  const apply = async () => {
    if (!plan || plan.total_file_count === 0) return;
    setBusy(true);
    setError(null);
    try {
      const resp = await api.applyCleanup(Array.from(selected));
      setOutcome({
        bytesFreed: resp.result.bytes_freed,
        deleted: resp.result.deleted.length,
        failed: resp.result.failed.length,
      });
    } catch (e) {
      if (e instanceof ApiError && e.status === 409) {
        const detail = e.body as { message?: string } | null;
        setError(
          detail?.message ??
            "Cannot clean up while jobs are pending or running. Wait for them to finish.",
        );
      } else {
        setError(e instanceof Error ? e.message : String(e));
      }
    } finally {
      setBusy(false);
    }
  };

  const totalLabel = plan
    ? `${plan.total_file_count} file${plan.total_file_count === 1 ? "" : "s"} · ${formatBytes(plan.total_bytes)}`
    : selected.size === 0
      ? "Nothing selected"
      : planLoading
        ? "Calculating..."
        : "0 files";

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="cleanup-dialog-title"
      className="fixed inset-0 z-50 flex items-center justify-center bg-background/70 p-4"
      onClick={onClose}
    >
      <Card
        className="w-full max-w-2xl shadow-xl"
        onClick={(e) => e.stopPropagation()}
      >
        <CardHeader>
          <CardTitle id="cleanup-dialog-title" className="flex items-center gap-2">
            <Trash2 className="size-5" />
            Reclaim disk space
          </CardTitle>
          <CardDescription>
            Original videos (and the symlinks under <code>raw/</code>) are
            never touched. <code>project.json</code> stays intact.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4 text-sm">
          {outcome ? (
            <div className="rounded-md border border-status-complete/40 bg-status-complete/10 p-4">
              <p className="font-semibold">
                Freed {formatBytes(outcome.bytesFreed)} across {outcome.deleted} file
                {outcome.deleted === 1 ? "" : "s"}.
              </p>
              {outcome.failed > 0 ? (
                <p className="mt-1 text-xs text-status-warning">
                  {outcome.failed} file{outcome.failed === 1 ? "" : "s"} could not
                  be deleted (see server logs).
                </p>
              ) : null}
              <div className="mt-3 flex justify-end">
                <Button onClick={onClose}>Close</Button>
              </div>
            </div>
          ) : (
            <>
              <div className="flex items-center justify-between">
                <div className="text-xs text-muted-foreground">
                  Toggle categories below; the total updates as you go.
                </div>
                <div className="flex gap-1">
                  <Button
                    type="button"
                    size="sm"
                    variant="ghost"
                    onClick={selectAllSafe}
                    disabled={busy}
                  >
                    Select all safe
                  </Button>
                  <Button
                    type="button"
                    size="sm"
                    variant="ghost"
                    onClick={deselectAll}
                    disabled={busy || selected.size === 0}
                  >
                    Clear
                  </Button>
                </div>
              </div>

              <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
                {SAFE_CATEGORIES.map((spec) => {
                  const totals = plan?.totals_by_category[spec.category];
                  const checked = selected.has(spec.category);
                  return (
                    <label
                      key={spec.category}
                      className="flex cursor-pointer items-start gap-2 rounded-md border border-border p-2 hover:bg-muted/40"
                    >
                      <input
                        type="checkbox"
                        className="mt-0.5"
                        checked={checked}
                        disabled={busy}
                        onChange={() => toggle(spec.category)}
                      />
                      <div className="flex-1 space-y-0.5">
                        <div className="flex items-center justify-between gap-2">
                          <span className="font-medium">{spec.label}</span>
                          {checked && totals ? (
                            <span className="text-xs text-muted-foreground">
                              {totals.file_count} · {formatBytes(totals.bytes)}
                            </span>
                          ) : null}
                        </div>
                        <p className="text-xs text-muted-foreground">{spec.help}</p>
                      </div>
                    </label>
                  );
                })}
              </div>

              <div className="rounded-md border border-status-warning/40 bg-status-warning/10 p-3">
                <div className="mb-2 flex items-center gap-2 text-xs font-semibold">
                  <AlertTriangle className="size-4" />
                  Destructive
                </div>
                <label className="flex cursor-pointer items-start gap-2">
                  <input
                    type="checkbox"
                    className="mt-0.5"
                    checked={selected.has(AUDIT_CATEGORY.category)}
                    disabled={busy}
                    onChange={() => toggle(AUDIT_CATEGORY.category)}
                  />
                  <div className="flex-1 space-y-0.5">
                    <div className="flex items-center justify-between gap-2">
                      <span className="font-medium">{AUDIT_CATEGORY.label}</span>
                      {selected.has(AUDIT_CATEGORY.category) && plan ? (
                        <span className="text-xs">
                          {plan.totals_by_category[AUDIT_CATEGORY.category]
                            ?.file_count ?? 0}
                          {" · "}
                          {formatBytes(
                            plan.totals_by_category[AUDIT_CATEGORY.category]?.bytes ?? 0,
                          )}
                        </span>
                      ) : null}
                    </div>
                    <p className="text-xs">{AUDIT_CATEGORY.help}</p>
                  </div>
                </label>
              </div>

              {error ? (
                <div className="rounded-md border border-destructive/40 bg-destructive/10 p-2 text-xs text-destructive">
                  {error}
                </div>
              ) : null}

              <div className="flex items-center justify-between border-t border-border pt-3">
                <div className="text-sm">
                  <span className="text-muted-foreground">Total: </span>
                  <span className="font-semibold">{totalLabel}</span>
                </div>
                <div className="flex gap-2">
                  <Button variant="ghost" onClick={onClose} disabled={busy}>
                    Cancel
                  </Button>
                  <Button
                    variant="destructive"
                    onClick={apply}
                    disabled={busy || !plan || plan.total_file_count === 0}
                  >
                    {busy
                      ? "Deleting..."
                      : plan && plan.total_file_count > 0
                        ? `Delete ${plan.total_file_count} file${plan.total_file_count === 1 ? "" : "s"}`
                        : "Delete"}
                  </Button>
                </div>
              </div>
            </>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
